import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { BrowserMultiFormatReader } from '@zxing/browser'
import { useAuthStore } from '../stores/authStore'
import { api } from '../api/client'
import { disconnectSocket } from '../lib/socket'
import { useScanStock, lookupStockItem } from '../api/stock'
import { useWarehouses } from '../api/warehouses'
import type { ScanResult, ScanPayload, ScanOperation } from '../api/stock'

const RESULT_TOAST_MS = 2000

function playBeep(success: boolean) {
  try {
    const ctx = new (window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext)()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    osc.connect(gain); gain.connect(ctx.destination)
    if (success) {
      // 3-note ascending chirp — louder + longer so operators hear it clearly
      // over warehouse noise and don't miss it when the 2s banner clears.
      osc.frequency.setValueAtTime(880, ctx.currentTime)
      osc.frequency.setValueAtTime(1175, ctx.currentTime + 0.10)
      osc.frequency.setValueAtTime(1480, ctx.currentTime + 0.20)
      osc.type = 'sine'
      gain.gain.setValueAtTime(0.6, ctx.currentTime)
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.45)
      osc.start(ctx.currentTime); osc.stop(ctx.currentTime + 0.45)
    } else {
      // Two-tone descending error buzz — distinctly lower than success so the
      // operator can tell them apart without looking at the screen.
      osc.frequency.setValueAtTime(220, ctx.currentTime)
      osc.frequency.setValueAtTime(180, ctx.currentTime + 0.15)
      osc.type = 'square'
      gain.gain.setValueAtTime(0.45, ctx.currentTime)
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.5)
      osc.start(ctx.currentTime); osc.stop(ctx.currentTime + 0.5)
    }
  } catch { /* noop */ }
}

// navigator.vibrate is only supported on Android (Chrome/Firefox) and a few
// other Android browsers. iOS Safari does not implement the Web Vibration
// API at all, so vibration silently does nothing there — no JS workaround
// can deliver true haptics on iOS via the web.
const HAS_VIBRATE = typeof navigator !== 'undefined' && typeof navigator.vibrate === 'function'

function vibrate(pattern: number | number[]) {
  if (!HAS_VIBRATE) return
  try { navigator.vibrate(pattern) } catch { /* noop */ }
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

function chipBtnStyle(active: boolean, activeBg: string, activeBorder: string): React.CSSProperties {
  return {
    flex: 1, padding: '8px 10px', borderRadius: 10,
    background: active ? activeBg : 'rgba(250,204,21,0.22)',
    border: `1px solid ${active ? activeBorder : 'rgba(250,204,21,0.7)'}`,
    color: '#fff', fontSize: 12, fontWeight: 700, cursor: 'pointer',
    whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
    minWidth: 0,
  }
}

// QR labels generated by /stock/labels encode JSON {id} — but be lenient and
// accept either a raw UUID string or { id: "<uuid>" } JSON.
function parseStockQr(text: string): string | null {
  const trimmed = text.trim()
  if (UUID_RE.test(trimmed)) return trimmed
  try {
    const obj = JSON.parse(trimmed)
    if (obj && typeof obj === 'object') {
      const id = (obj as { id?: unknown }).id
      if (typeof id === 'string' && UUID_RE.test(id)) return id
    }
  } catch { /* not JSON */ }
  return null
}

const WH_KEY = 'stock-scan-warehouseId'
const OP_KEY = 'stock-scan-operation'
const OP_PICKED_KEY = 'stock-scan-op-picked'
const SCAN_MODE_KEY = 'stock-scan-mode'

type ScanMode = 'single' | 'bulk'

// Bulk Scan v2: scans accumulate in a local queue (lookup-only, status not
// touched on the backend) until the operator presses "Confirm All". The
// confirm popup shows total boxes + total kg/pcs aggregated from queue items.
// On confirm, each queued item fires a real /stock/scan mutation and the
// result is appended to the post-commit log.
interface BulkQueueEntry {
  ts: number
  id: string
  productName: string
  productCode: string
  qty: number
  unit: 'KG' | 'PCS'
}

interface BulkResultEntry {
  ts: number
  id: string
  productName?: string
  qty?: number
  unit?: 'KG' | 'PCS'
  type?: 'IN' | 'USED' | 'TRANSFER' | 'ADJUSTMENT_OUT'
  noChange?: boolean
  error?: string
}

const OPERATIONS: { value: ScanOperation; label: string; subtitle: string; color: string }[] = [
  { value: 'IN',       label: 'Stock In',       subtitle: 'Receive into warehouse', color: '#22c55e' },
  { value: 'OUT',      label: 'Stock Out',      subtitle: 'Mark as used / shipped',  color: '#ef4444' },
  { value: 'TRANSFER', label: 'Stock Transfer', subtitle: 'Move between warehouses', color: '#3b82f6' },
]

export default function StockScan() {
  const navigate = useNavigate()
  const user = useAuthStore((s) => s.user)
  const setUser = useAuthStore((s) => s.setUser)
  const { data: warehouses = [] } = useWarehouses()

  const videoRef = useRef<HTMLVideoElement>(null)
  const streamRef = useRef<MediaStream | null>(null)
  const controlsRef = useRef<{ stop: () => void } | null>(null)
  const lockedRef = useRef(false)
  // Single-mode: after a scan resolves (success OR error), keep the ID so the
  // camera doesn't immediately re-detect the same QR (which is still in the
  // viewfinder) and pop the confirm modal again — that auto-re-fire was
  // causing brand-new PENDING labels to flip IN_STOCK on the first attempt
  // and then throw "Already stocked at …" on the silent second attempt.
  // Reset on: different QR detected, Cancel pressed, camera closed/reopened.
  const lastResolvedIdRef = useRef<string | null>(null)

  const [operation, setOperation] = useState<ScanOperation>(() => {
    const stored = localStorage.getItem(OP_KEY) as ScanOperation | null
    return stored && ['IN', 'OUT', 'TRANSFER'].includes(stored) ? stored : 'IN'
  })
  // Whether the operator has explicitly confirmed an Operation choice in
  // this device. We persist a separate flag (not just the operation value)
  // so a fresh device — where localStorage defaults the value to 'IN' —
  // still forces the operator through the picker before the camera opens.
  const [opPicked, setOpPicked] = useState<boolean>(() => localStorage.getItem(OP_PICKED_KEY) === '1')
  const [warehouseId, setWarehouseId] = useState<string>(() => localStorage.getItem(WH_KEY) ?? '')
  const [toWarehouseId, setToWarehouseId] = useState<string>('')
  const [showOpPicker, setShowOpPicker] = useState(false)
  const [showWhPicker, setShowWhPicker] = useState<null | 'from' | 'to'>(null)
  const [cameraOn, setCameraOn] = useState(false)
  const [cameraError, setCameraError] = useState<string | null>(null)
  const [lastResult, setLastResult] = useState<ScanResult | null>(null)
  const [errorMessage, setErrorMessage] = useState<string | null>(null)
  const [debugRaw, setDebugRaw] = useState<string | null>(null)
  const [showDebug, setShowDebug] = useState(false)
  const [pendingScan, setPendingScan] = useState<{ id: string } | null>(null)
  const pendingRef = useRef<{ id: string } | null>(null)
  const [scanMode, setScanMode] = useState<ScanMode>(() => {
    const stored = localStorage.getItem(SCAN_MODE_KEY)
    return stored === 'bulk' ? 'bulk' : 'single'
  })
  const scanModeRef = useRef<ScanMode>(scanMode)
  const [bulkQueue, setBulkQueue] = useState<BulkQueueEntry[]>([])
  const bulkQueueRef = useRef<BulkQueueEntry[]>([])
  const [bulkResults, setBulkResults] = useState<BulkResultEntry[]>([])
  const [showBulkConfirm, setShowBulkConfirm] = useState(false)
  const [isCommittingBulk, setIsCommittingBulk] = useState(false)

  useEffect(() => { pendingRef.current = pendingScan }, [pendingScan])
  useEffect(() => { scanModeRef.current = scanMode }, [scanMode])
  useEffect(() => { localStorage.setItem(SCAN_MODE_KEY, scanMode) }, [scanMode])
  useEffect(() => { bulkQueueRef.current = bulkQueue }, [bulkQueue])

  const scanMutation = useScanStock()

  // Auto-dismiss the single-mode result / error banner after 7s so the bottom
  // strip doesn't stay occupied between scans. Bulk mode keeps its log
  // persistent because the operator may need to review what happened.
  useEffect(() => {
    if (!lastResult && !errorMessage) return
    const t = window.setTimeout(() => {
      setLastResult(null); setErrorMessage(null)
    }, RESULT_TOAST_MS)
    return () => window.clearTimeout(t)
  }, [lastResult, errorMessage])

  const bulkBoxCount = bulkQueue.length
  const bulkKgTotal = useMemo(
    () => bulkQueue.filter((q) => q.unit === 'KG').reduce((s, q) => s + q.qty, 0),
    [bulkQueue],
  )
  const bulkPcsTotal = useMemo(
    () => bulkQueue.filter((q) => q.unit === 'PCS').reduce((s, q) => s + q.qty, 0),
    [bulkQueue],
  )
  const bulkTotalsText = useMemo(() => {
    const parts: string[] = []
    if (bulkKgTotal > 0) parts.push(`${formatQty(bulkKgTotal)} kg`)
    if (bulkPcsTotal > 0) parts.push(`${formatQty(bulkPcsTotal)} pcs`)
    return parts.join(' + ')
  }, [bulkKgTotal, bulkPcsTotal])
  const bulkResultSuccess = useMemo(() => bulkResults.filter((e) => !e.error).length, [bulkResults])
  const bulkResultErrors = useMemo(() => bulkResults.filter((e) => e.error).length, [bulkResults])

  useEffect(() => {
    if (warehouseId) localStorage.setItem(WH_KEY, warehouseId)
  }, [warehouseId])
  useEffect(() => {
    localStorage.setItem(OP_KEY, operation)
  }, [operation])
  useEffect(() => {
    localStorage.setItem(OP_PICKED_KEY, opPicked ? '1' : '0')
  }, [opPicked])

  useEffect(() => {
    if (!warehouseId && warehouses.length === 1) setWarehouseId(warehouses[0].id)
  }, [warehouses, warehouseId])

  const selectedWarehouse = warehouses.find((w) => w.id === warehouseId)
  const destinationWarehouse = warehouses.find((w) => w.id === toWarehouseId)
  const opMeta = OPERATIONS.find((o) => o.value === operation)!
  const needsToWarehouse = operation === 'TRANSFER'

  const ready = !!warehouseId && (!needsToWarehouse || !!toWarehouseId) && warehouseId !== toWarehouseId

  const stopCamera = useCallback(() => {
    controlsRef.current?.stop()
    controlsRef.current = null
    streamRef.current?.getTracks().forEach((t) => t.stop())
    streamRef.current = null
    lastResolvedIdRef.current = null
    setCameraOn(false)
  }, [])

  const startCamera = useCallback(async () => {
    setCameraError(null); setErrorMessage(null)
    if (!opPicked) { setShowOpPicker(true); return }
    if (!warehouseId) { setShowWhPicker('from'); return }
    if (needsToWarehouse && !toWarehouseId) { setShowWhPicker('to'); return }
    if (needsToWarehouse && warehouseId === toWarehouseId) {
      setErrorMessage('Source and destination warehouses must differ.')
      return
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment', width: { ideal: 1280 }, height: { ideal: 720 } },
      })
      streamRef.current = stream
      setCameraOn(true)
    } catch (err: unknown) {
      const name = (err as { name?: string })?.name
      setCameraError(
        name === 'NotAllowedError' ? 'Camera permission denied. Please allow camera access.' :
        name === 'NotFoundError' ? 'No camera found on this device.' :
        'Could not open camera.',
      )
    }
  }, [warehouseId, toWarehouseId, needsToWarehouse, opPicked])

  useEffect(() => {
    if (!cameraOn || !videoRef.current || !streamRef.current) return
    const video = videoRef.current
    const stream = streamRef.current
    video.srcObject = stream
    const reader = new BrowserMultiFormatReader()

    video.play().then(() => {
      reader.decodeFromStream(stream, video, (result, _err, controls) => {
        if (controls && !controlsRef.current) controlsRef.current = controls
        if (!result || lockedRef.current || pendingRef.current) return
        const text = result.getText().trim()
        setDebugRaw(text)
        const id = parseStockQr(text)
        if (!id) {
          setErrorMessage('Unknown QR — not a stock label.')
          playBeep(false); vibrate([80, 60, 80])
          window.setTimeout(() => setErrorMessage(null), 1800)
          return
        }
        if (!ready) {
          setErrorMessage('Pick operation and warehouse(s) first.')
          return
        }
        if (scanModeRef.current === 'bulk') {
          // Bulk mode — preview only. Look up the label so we can show
          // accurate qty/unit in the confirm popup, queue it, and wait for
          // the operator to press "Confirm All" before any mutation runs.
          if (bulkQueueRef.current.some((q) => q.id === id)) {
            // Same QR already queued — debounce silently to avoid noise.
            lockedRef.current = true
            window.setTimeout(() => { lockedRef.current = false }, 800)
            return
          }
          lockedRef.current = true
          playBeep(true); vibrate([60, 40, 80])
          lookupStockItem(id).then((item) => {
            setBulkQueue((prev) => {
              if (prev.some((q) => q.id === id)) return prev
              return [{
                ts: Date.now(), id,
                productName: item.productName,
                productCode: item.productCode,
                qty: item.quantity,
                unit: item.unit,
              }, ...prev]
            })
            window.setTimeout(() => { lockedRef.current = false }, 800)
          }).catch((err: unknown) => {
            const msg = (err as { response?: { data?: { error?: string } } })?.response?.data?.error
              ?? 'Unknown label'
            setErrorMessage(msg)
            playBeep(false); vibrate([80, 60, 80])
            window.setTimeout(() => { lockedRef.current = false }, 800)
          })
          return
        }
        // Single mode — alert user and open the confirmation modal.
        // Silent skip if this is the same QR we just resolved (success or
        // error). Pointing at any other QR clears the guard.
        if (id === lastResolvedIdRef.current) return
        lastResolvedIdRef.current = null
        playBeep(true); vibrate([80, 60, 140])
        setPendingScan({ id })
      }).then((controls) => { if (!controlsRef.current) controlsRef.current = controls })
        .catch(() => { /* noop */ })
    }).catch(() => {
      setCameraError('Could not start video stream.')
      setCameraOn(false)
    })

    return () => {
      try { (reader as unknown as { stopAsyncDecode?: () => void }).stopAsyncDecode?.() } catch { /* noop */ }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cameraOn, warehouseId, toWarehouseId, operation, needsToWarehouse, ready])

  useEffect(() => () => stopCamera(), [stopCamera])

  function cancelScan() {
    // Cancel = operator decided not to commit this QR; allow them to scan
    // the same sticker again immediately (e.g. to verify they grabbed the
    // right box) by clearing the resolved-id guard.
    lastResolvedIdRef.current = null
    setPendingScan(null)
  }

  function confirmScan() {
    if (!pendingScan) return
    const scannedId = pendingScan.id
    const payload: ScanPayload = {
      id: scannedId,
      operation,
      warehouseId,
      ...(needsToWarehouse ? { toWarehouseId } : {}),
    }
    scanMutation.mutate(payload, {
      onSuccess: (data) => {
        setLastResult(data); setErrorMessage(null)
        setPendingScan(null)
        lastResolvedIdRef.current = scannedId
        // Strong 3-pulse success vibration (~870ms) — clearly distinct from
        // error pattern and noticeable in a glove without looking at screen.
        playBeep(true); vibrate([250, 100, 200, 100, 200])
      },
      onError: (err: unknown) => {
        const msg = (err as { response?: { data?: { error?: string } } })?.response?.data?.error
          ?? 'Scan failed'
        setErrorMessage(msg); setLastResult(null)
        setPendingScan(null)
        lastResolvedIdRef.current = scannedId
        // Longer 4-pulse error vibration (~1180ms) — heavier than success so
        // the operator feels something is wrong even mid-stride.
        playBeep(false); vibrate([180, 100, 180, 100, 180, 100, 280])
      },
    })
  }

  async function commitBulkQueue() {
    if (bulkQueue.length === 0 || isCommittingBulk) return
    setIsCommittingBulk(true)
    setShowBulkConfirm(false)
    const queueSnapshot = [...bulkQueue]
    // Commit oldest first so the result log reads in scan order.
    const ordered = queueSnapshot.slice().reverse()
    const newResults: BulkResultEntry[] = []
    for (const item of ordered) {
      const payload: ScanPayload = {
        id: item.id, operation, warehouseId,
        ...(needsToWarehouse ? { toWarehouseId } : {}),
      }
      try {
        const data = await scanMutation.mutateAsync(payload)
        newResults.unshift({
          ts: Date.now(), id: item.id,
          productName: data.item.productName,
          qty: data.item.quantity,
          unit: data.item.unit,
          type: data.type,
          noChange: data.noChange,
        })
      } catch (err: unknown) {
        const msg = (err as { response?: { data?: { error?: string } } })?.response?.data?.error
          ?? 'Scan failed'
        newResults.unshift({
          ts: Date.now(), id: item.id,
          productName: item.productName,
          qty: item.qty,
          unit: item.unit,
          error: msg,
        })
      }
    }
    setBulkResults((prev) => [...newResults, ...prev].slice(0, 100))
    setBulkQueue([])
    setIsCommittingBulk(false)
    const ok = newResults.filter((r) => !r.error).length
    const bad = newResults.length - ok
    if (bad === 0) { playBeep(true); vibrate([250, 100, 200, 100, 200]) }
    else { playBeep(false); vibrate([180, 100, 180, 100, 180, 100, 280]) }
  }

  async function handleLogout() {
    try { await api.post('/auth/logout') } catch { /* ignore */ }
    disconnectSocket()
    setUser(null)
    navigate('/scan', { replace: true })
  }

  const resultStyle = resultToneStyle(lastResult)

  return (
    <div style={{ minHeight: '100dvh', display: 'flex', flexDirection: 'column', background: '#0f172a', color: '#fff' }}>
      <header style={{
        padding: '6px 14px', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        background: 'rgba(15,23,42,0.95)', borderBottom: '1px solid rgba(148,163,184,0.2)',
      }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
          <div style={{ fontSize: 12, fontWeight: 700, letterSpacing: '0.04em' }}>STOCK SCAN</div>
          <div style={{ fontSize: 10, color: '#94a3b8' }}>{user?.username}</div>
        </div>
        <button
          onClick={handleLogout}
          style={{ background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.15)',
            color: '#f1f5f9', padding: '5px 12px', borderRadius: 8, fontSize: 11, fontWeight: 600, cursor: 'pointer' }}
        >Sign Out</button>
      </header>

      <div
        style={cameraOn
          ? { position: 'fixed', inset: 0, background: '#000', zIndex: 40, overflow: 'hidden' }
          : { flex: 1, position: 'relative', overflow: 'hidden', background: '#000' }}
      >
        {cameraOn ? (
          <>
            <video ref={videoRef} playsInline muted style={{ width: '100%', height: '100%', objectFit: 'cover' }} />

            {/* Scan frame */}
            <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', pointerEvents: 'none' }}>
              <div style={{ width: '78%', maxWidth: 320, aspectRatio: '1/1', border: `3px solid ${opMeta.color}d9`, borderRadius: 14, boxShadow: '0 0 0 9999px rgba(0,0,0,0.55)' }} />
            </div>

            {/* Floating top bar — close + Op + WH chips + Mode toggle */}
            <div style={{
              position: 'absolute', top: 0, left: 0, right: 0, zIndex: 12,
              padding: '10px 10px 12px',
              background: 'linear-gradient(to bottom, rgba(15,23,42,0.92), rgba(15,23,42,0))',
              display: 'flex', flexDirection: 'column', gap: 8,
            }}>
              <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                <button
                  onClick={stopCamera} aria-label="Close camera"
                  style={{
                    width: 42, height: 42, borderRadius: 21,
                    background: 'rgba(15,23,42,0.92)', border: '1px solid rgba(255,255,255,0.25)',
                    color: '#fff', fontSize: 22, fontWeight: 700, cursor: 'pointer',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    paddingBottom: 4, flexShrink: 0,
                  }}
                >×</button>
                <div style={{ display: 'flex', gap: 6, flex: 1, minWidth: 0 }}>
                  <button onClick={() => setShowOpPicker(true)} style={chipBtnStyle(opPicked, `${opMeta.color}38`, `${opMeta.color}88`)}>
                    {opPicked ? opMeta.label : 'Pick op'}
                  </button>
                  <button onClick={() => setShowWhPicker('from')} style={chipBtnStyle(!!selectedWarehouse, 'rgba(59,130,246,0.22)', 'rgba(59,130,246,0.5)')}>
                    {selectedWarehouse?.name ?? 'WH?'}
                  </button>
                  {needsToWarehouse && (
                    <button onClick={() => setShowWhPicker('to')} style={chipBtnStyle(!!destinationWarehouse, 'rgba(59,130,246,0.22)', 'rgba(59,130,246,0.5)')}>
                      → {destinationWarehouse?.name ?? 'Dest'}
                    </button>
                  )}
                </div>
              </div>
              <div style={{ display: 'flex', background: 'rgba(15,23,42,0.85)', border: '1px solid rgba(255,255,255,0.12)', borderRadius: 10, padding: 3 }}>
                {(['single', 'bulk'] as ScanMode[]).map((m) => (
                  <button
                    key={m}
                    onClick={() => { setScanMode(m); if (m === 'single') { setBulkQueue([]); setBulkResults([]) } }}
                    style={{
                      flex: 1, padding: '7px 0', borderRadius: 8, border: 'none',
                      background: scanMode === m ? opMeta.color : 'transparent',
                      color: scanMode === m ? '#fff' : '#94a3b8',
                      fontSize: 12, fontWeight: 700, cursor: 'pointer',
                    }}
                  >{m === 'single' ? 'Single' : 'Bulk'}</button>
                ))}
              </div>
            </div>

            {/* Floating bottom — single result or bulk log */}
            <div style={{
              position: 'absolute', bottom: 0, left: 0, right: 0, zIndex: 12,
              padding: '14px 12px 18px',
              background: 'linear-gradient(to top, rgba(15,23,42,0.95), rgba(15,23,42,0))',
              maxHeight: '45%', overflow: 'hidden', display: 'flex', flexDirection: 'column', gap: 6,
            }}>
              {scanMode === 'bulk' ? (
                <>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '4px 6px', gap: 8 }}>
                    <div style={{ display: 'flex', flexDirection: 'column', minWidth: 0 }}>
                      <div style={{ fontSize: 12, fontWeight: 700, letterSpacing: '0.06em', color: '#cbd5e1' }}>
                        QUEUE · {bulkBoxCount} {bulkBoxCount === 1 ? 'box' : 'boxes'}
                        {bulkTotalsText && <> · {bulkTotalsText}</>}
                      </div>
                      {bulkResults.length > 0 && (
                        <div style={{ fontSize: 10, color: '#94a3b8' }}>
                          Last batch: {bulkResultSuccess} done{bulkResultErrors > 0 ? ` · ${bulkResultErrors} error${bulkResultErrors > 1 ? 's' : ''}` : ''}
                        </div>
                      )}
                    </div>
                    {(bulkQueue.length > 0 || bulkResults.length > 0) && (
                      <button
                        onClick={() => { setBulkQueue([]); setBulkResults([]); setErrorMessage(null) }}
                        disabled={isCommittingBulk}
                        style={{ background: 'transparent', border: 'none', color: '#94a3b8', fontSize: 11, cursor: 'pointer', textDecoration: 'underline', flexShrink: 0 }}
                      >Clear</button>
                    )}
                  </div>

                  {errorMessage && (
                    <div style={{ background: 'rgba(239,68,68,0.22)', border: '1px solid rgba(239,68,68,0.5)', color: '#fecaca', padding: '6px 10px', borderRadius: 8, fontSize: 12, fontWeight: 600 }}>
                      ✗ {errorMessage}
                    </div>
                  )}

                  <div style={{ display: 'flex', flexDirection: 'column', gap: 4, maxHeight: 140, overflowY: 'auto' }}>
                    {bulkQueue.slice(0, 5).map((e) => (
                      <div key={e.ts} style={{
                        padding: '6px 10px', borderRadius: 8, fontSize: 12, color: '#fff',
                        background: 'rgba(148,163,184,0.18)', border: '1px solid rgba(148,163,184,0.4)',
                      }}>
                        + {e.productName} · {formatQty(e.qty)} {e.unit === 'KG' ? 'kg' : 'pcs'}
                      </div>
                    ))}
                    {bulkQueue.length === 0 && bulkResults.length > 0 && bulkResults.slice(0, 5).map((e) => (
                      <div key={e.ts} style={{
                        padding: '6px 10px', borderRadius: 8, fontSize: 12, color: '#fff',
                        background: e.error
                          ? 'rgba(239,68,68,0.22)'
                          : e.noChange
                            ? 'rgba(250,204,21,0.22)'
                            : 'rgba(34,197,94,0.22)',
                        border: `1px solid ${e.error ? 'rgba(239,68,68,0.45)' : e.noChange ? 'rgba(250,204,21,0.5)' : 'rgba(34,197,94,0.45)'}`,
                      }}>
                        {e.error
                          ? <>✗ {e.productName ?? e.id.slice(0, 8)} · {e.error}</>
                          : <>✓ {e.productName ?? e.id.slice(0, 8)} · {e.qty && formatQty(e.qty)}{' '}{e.unit === 'KG' ? 'kg' : 'pcs'}{e.noChange ? ' · no change' : ''}</>
                        }
                      </div>
                    ))}
                    {bulkQueue.length === 0 && bulkResults.length === 0 && (
                      <div style={{ fontSize: 12, color: '#94a3b8', textAlign: 'center', padding: '8px 0' }}>
                        Scan boxes one after another — they queue here. Press Confirm when done.
                      </div>
                    )}
                  </div>

                  {bulkQueue.length > 0 && (
                    <button
                      onClick={() => setShowBulkConfirm(true)}
                      disabled={isCommittingBulk}
                      style={{
                        marginTop: 4, padding: '12px 14px', borderRadius: 12,
                        background: `linear-gradient(135deg, ${opMeta.color}, ${opMeta.color}dd)`,
                        border: 'none', color: '#fff', fontWeight: 800, fontSize: 14, cursor: 'pointer',
                        boxShadow: `0 4px 16px ${opMeta.color}66`,
                        opacity: isCommittingBulk ? 0.6 : 1,
                      }}
                    >
                      {isCommittingBulk
                        ? 'Working…'
                        : `Confirm ${opMeta.label} · ${bulkBoxCount} ${bulkBoxCount === 1 ? 'box' : 'boxes'}`}
                    </button>
                  )}
                </>
              ) : (
                <>
                  {errorMessage ? (
                    <div style={{ background: 'rgba(239,68,68,0.22)', border: '1px solid rgba(239,68,68,0.5)', color: '#fecaca', padding: 12, borderRadius: 10 }}>
                      <div style={{ fontWeight: 700, fontSize: 13 }}>✗ {errorMessage}</div>
                    </div>
                  ) : lastResult ? (
                    <div style={{
                      background: resultStyle.bg, border: `1px solid ${resultStyle.border}`, color: resultStyle.text,
                      padding: 12, borderRadius: 10, display: 'flex', flexDirection: 'column', gap: 2,
                    }}>
                      <div style={{ fontWeight: 800, fontSize: 14 }}>{resultStyle.title}</div>
                      {lastResult.message && (
                        <div style={{ fontSize: 11, opacity: 0.85 }}>{lastResult.message}</div>
                      )}
                      <div style={{ fontSize: 12 }}>
                        {lastResult.item.productName} · {lastResult.item.quantity}{' '}
                        {lastResult.item.unit === 'KG' ? 'kg' : 'pcs'}
                      </div>
                    </div>
                  ) : (
                    <div style={{ color: '#94a3b8', fontSize: 12, textAlign: 'center', padding: '6px 0' }}>
                      Aim at a QR — single scan asks for confirmation.
                    </div>
                  )}
                </>
              )}
              {showDebug && debugRaw && (
                <div style={{
                  background: 'rgba(0,0,0,0.85)', color: '#bbf7d0', padding: '6px 10px',
                  borderRadius: 8, fontSize: 10, fontFamily: 'monospace',
                  maxHeight: 60, overflow: 'auto', wordBreak: 'break-all',
                }}>
                  <span style={{ color: '#94a3b8', fontWeight: 700 }}>RAW</span> {debugRaw}
                </div>
              )}
            </div>
          </>
        ) : (
          <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 16, padding: 20 }}>
            <div style={{ fontSize: 52 }}>📦</div>
            <div style={{ fontSize: 17, fontWeight: 700, textAlign: 'center' }}>{opPicked ? opMeta.label : 'Pick an operation first'}</div>
            <div style={{ fontSize: 13, color: '#94a3b8', textAlign: 'center', maxWidth: 280 }}>
              {opPicked && opMeta.subtitle}
              {opPicked && selectedWarehouse && !needsToWarehouse && <> at <strong style={{ color: '#fff' }}>{selectedWarehouse.name}</strong></>}
              {opPicked && selectedWarehouse && needsToWarehouse && destinationWarehouse && (
                <> · <strong style={{ color: '#fff' }}>{selectedWarehouse.name}</strong> → <strong style={{ color: '#fff' }}>{destinationWarehouse.name}</strong></>
              )}
            </div>
            {cameraError && (
              <div style={{ background: 'rgba(239,68,68,0.15)', border: '1px solid rgba(239,68,68,0.4)', color: '#fecaca', padding: '10px 14px', borderRadius: 8, fontSize: 13, maxWidth: 320, textAlign: 'center' }}>
                {cameraError}
              </div>
            )}
            <button
              onClick={startCamera}
              style={{ marginTop: 4, padding: '14px 28px',
                background: `linear-gradient(135deg, ${opMeta.color}, ${opMeta.color}dd)`, color: '#fff', border: 'none',
                borderRadius: 12, fontSize: 15, fontWeight: 700, cursor: 'pointer',
                boxShadow: `0 4px 18px ${opMeta.color}66`, minHeight: 52, minWidth: 180 }}
            >Open Camera</button>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, color: '#94a3b8', cursor: 'pointer' }}>
              <input type="checkbox" checked={showDebug} onChange={(e) => setShowDebug(e.target.checked)} />
              Show raw QR (debug)
            </label>
          </div>
        )}
      </div>

      {!cameraOn && (
        <>
          {(errorMessage || lastResult) && (
            <div style={{ padding: '10px 16px', background: '#0f172a', borderTop: '1px solid rgba(148,163,184,0.15)' }}>
              {errorMessage ? (
                <div style={{ background: 'rgba(239,68,68,0.15)', border: '1px solid rgba(239,68,68,0.4)', color: '#fecaca', padding: 14, borderRadius: 10 }}>
                  <div style={{ fontWeight: 700, fontSize: 14 }}>✗ {errorMessage}</div>
                </div>
              ) : lastResult ? (
                <div style={{
                  background: resultStyle.bg, border: `1px solid ${resultStyle.border}`, color: resultStyle.text,
                  padding: 14, borderRadius: 10, display: 'flex', flexDirection: 'column', gap: 4,
                }}>
                  <div style={{ fontWeight: 800, fontSize: 15 }}>{resultStyle.title}</div>
                  {lastResult.message && (
                    <div style={{ fontSize: 12, opacity: 0.85 }}>{lastResult.message}</div>
                  )}
                  <div style={{ fontSize: 13 }}>
                    {lastResult.item.productName} · {lastResult.item.quantity}{' '}
                    {lastResult.item.unit === 'KG' ? 'kg' : 'pcs'} · Batch {lastResult.item.batchNumber}
                  </div>
                </div>
              ) : null}
            </div>
          )}

          <div style={{ padding: '8px 14px 14px', display: 'flex', flexDirection: 'column', gap: 8, background: '#0f172a', borderTop: '1px solid rgba(148,163,184,0.1)' }}>
            {/* Scan mode toggle */}
            <div style={{ display: 'flex', background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 10, padding: 3 }}>
              {(['single', 'bulk'] as ScanMode[]).map((m) => (
                <button
                  key={m}
                  onClick={() => { setScanMode(m); if (m === 'single') { setBulkQueue([]); setBulkResults([]) } }}
                  style={{
                    flex: 1, padding: '9px 0', borderRadius: 8, border: 'none',
                    background: scanMode === m ? opMeta.color : 'transparent',
                    color: scanMode === m ? '#fff' : '#94a3b8',
                    fontSize: 13, fontWeight: 700, cursor: 'pointer',
                  }}
                >{m === 'single' ? 'Single Scan' : 'Bulk Scan'}</button>
              ))}
            </div>

            {/* Operation selector */}
            <button
              onClick={() => setShowOpPicker(true)}
              style={{
                padding: '10px 14px', borderRadius: 10,
                background: opPicked ? `${opMeta.color}28` : 'rgba(250,204,21,0.2)',
                border: `1px solid ${opPicked ? `${opMeta.color}66` : 'rgba(250,204,21,0.7)'}`,
                color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer',
                display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10,
              }}
            >
              <span style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}>
                <span style={{ fontSize: 10, opacity: 0.8, fontWeight: 500 }}>OPERATION{opPicked ? '' : ' — required'}</span>
                <span style={{ fontSize: 14, fontWeight: 700 }}>{opPicked ? opMeta.label : 'Pick operation'}</span>
              </span>
              <span style={{ fontSize: 11, opacity: 0.8 }}>{opPicked ? 'change ›' : 'pick ›'}</span>
            </button>

            {/* Warehouse selector (source/current) */}
            <button
              onClick={() => setShowWhPicker('from')}
              style={{
                padding: '10px 14px', borderRadius: 10,
                background: selectedWarehouse ? 'rgba(59,130,246,0.16)' : 'rgba(239,68,68,0.18)',
                border: `1px solid ${selectedWarehouse ? 'rgba(59,130,246,0.4)' : 'rgba(239,68,68,0.5)'}`,
                color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer',
                display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10,
              }}
            >
              <span style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}>
                <span style={{ fontSize: 10, opacity: 0.8, fontWeight: 500 }}>
                  {needsToWarehouse ? 'FROM WAREHOUSE' : 'WAREHOUSE'}
                </span>
                <span style={{ fontSize: 14, fontWeight: 700 }}>
                  {selectedWarehouse ? selectedWarehouse.name : 'Select warehouse'}
                </span>
              </span>
              <span style={{ fontSize: 11, opacity: 0.8 }}>change ›</span>
            </button>

            {/* Destination warehouse (only for Transfer) */}
            {needsToWarehouse && (
              <button
                onClick={() => setShowWhPicker('to')}
                style={{
                  padding: '10px 14px', borderRadius: 10,
                  background: destinationWarehouse ? 'rgba(59,130,246,0.16)' : 'rgba(239,68,68,0.18)',
                  border: `1px solid ${destinationWarehouse ? 'rgba(59,130,246,0.4)' : 'rgba(239,68,68,0.5)'}`,
                  color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer',
                  display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10,
                }}
              >
                <span style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}>
                  <span style={{ fontSize: 10, opacity: 0.8, fontWeight: 500 }}>TO WAREHOUSE</span>
                  <span style={{ fontSize: 14, fontWeight: 700 }}>
                    {destinationWarehouse ? destinationWarehouse.name : 'Select destination'}
                  </span>
                </span>
                <span style={{ fontSize: 11, opacity: 0.8 }}>change ›</span>
              </button>
            )}
          </div>
        </>
      )}

      {/* Operation picker bottom sheet */}
      {showOpPicker && (
        <div
          onClick={() => setShowOpPicker(false)}
          style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', zIndex: 50, display: 'flex', alignItems: 'flex-end' }}
        >
          <div onClick={(e) => e.stopPropagation()} style={{ width: '100%', background: '#0f172a', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 16, maxHeight: '70vh', overflow: 'auto' }}>
            <div style={{ fontSize: 14, fontWeight: 700, marginBottom: 10 }}>Pick operation</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {OPERATIONS.map((o) => (
                <button
                  key={o.value}
                  onClick={() => { setOperation(o.value); setOpPicked(true); setShowOpPicker(false); if (o.value !== 'TRANSFER') setToWarehouseId('') }}
                  style={{
                    padding: '12px 14px', textAlign: 'left', borderRadius: 10,
                    background: operation === o.value ? `${o.color}33` : 'rgba(255,255,255,0.05)',
                    border: `1px solid ${operation === o.value ? `${o.color}88` : 'rgba(255,255,255,0.1)'}`,
                    color: '#fff', fontSize: 14, fontWeight: 600, cursor: 'pointer',
                  }}
                >
                  <div>{o.label}</div>
                  <div style={{ fontSize: 11, opacity: 0.7, fontWeight: 400 }}>{o.subtitle}</div>
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Warehouse picker bottom sheet */}
      {showWhPicker && (
        <div
          onClick={() => setShowWhPicker(null)}
          style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', zIndex: 50, display: 'flex', alignItems: 'flex-end' }}
        >
          <div onClick={(e) => e.stopPropagation()} style={{ width: '100%', background: '#0f172a', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 16, maxHeight: '70vh', overflow: 'auto' }}>
            <div style={{ fontSize: 14, fontWeight: 700, marginBottom: 10 }}>
              {showWhPicker === 'to' ? 'Pick destination warehouse' : 'Pick warehouse'}
            </div>
            {warehouses.length === 0 ? (
              <div style={{ color: '#94a3b8', fontSize: 13 }}>No warehouses configured. Ask an admin to create one.</div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                {warehouses.map((w) => {
                  const selectedId = showWhPicker === 'to' ? toWarehouseId : warehouseId
                  return (
                    <button
                      key={w.id}
                      onClick={() => {
                        if (showWhPicker === 'to') setToWarehouseId(w.id)
                        else setWarehouseId(w.id)
                        setShowWhPicker(null)
                      }}
                      style={{
                        padding: '12px 14px', textAlign: 'left', borderRadius: 10,
                        background: selectedId === w.id ? 'rgba(59,130,246,0.25)' : 'rgba(255,255,255,0.05)',
                        border: `1px solid ${selectedId === w.id ? 'rgba(59,130,246,0.5)' : 'rgba(255,255,255,0.1)'}`,
                        color: '#fff', fontSize: 14, fontWeight: 600, cursor: 'pointer',
                      }}
                    >
                      <div>{w.name}</div>
                      <div style={{ fontSize: 11, opacity: 0.7, fontWeight: 400 }}>{w.address}</div>
                    </button>
                  )
                })}
              </div>
            )}
          </div>
        </div>
      )}

      {/* Scan confirmation modal — shown when a QR is detected and we are
          waiting for the operator to confirm the action. Camera keeps
          running but pendingRef prevents re-detection until resolved. */}
      {pendingScan && (
        <div
          style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.78)', zIndex: 60, display: 'flex', alignItems: 'flex-end' }}
        >
          <div style={{ width: '100%', background: '#0f172a', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 20, paddingBottom: 24, display: 'flex', flexDirection: 'column', gap: 14 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <div style={{ width: 38, height: 38, borderRadius: 19, background: `${opMeta.color}33`, border: `1px solid ${opMeta.color}88`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20 }}>📦</div>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 16, fontWeight: 800 }}>Confirm scan</div>
                <div style={{ fontSize: 11, color: '#94a3b8' }}>QR detected — review and confirm.</div>
              </div>
            </div>

            <div style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(148,163,184,0.18)', borderRadius: 12, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
              <Row label="Operation" value={opMeta.label} valueColor={opMeta.color} />
              {needsToWarehouse ? (
                <>
                  <Row label="From" value={selectedWarehouse?.name ?? '—'} />
                  <Row label="To" value={destinationWarehouse?.name ?? '—'} />
                </>
              ) : (
                <Row label="Warehouse" value={selectedWarehouse?.name ?? '—'} />
              )}
              <Row label="QR" value={pendingScan.id.slice(0, 8) + '…'} mono />
            </div>

            <div style={{ display: 'flex', gap: 10 }}>
              <button
                onClick={cancelScan}
                disabled={scanMutation.isPending}
                style={{
                  flex: 1, padding: '14px 12px', borderRadius: 12,
                  background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.15)',
                  color: '#e2e8f0', fontWeight: 700, fontSize: 15, cursor: 'pointer',
                  opacity: scanMutation.isPending ? 0.5 : 1,
                }}
              >Cancel</button>
              <button
                onClick={confirmScan}
                disabled={scanMutation.isPending}
                style={{
                  flex: 2, padding: '14px 12px', borderRadius: 12,
                  background: `linear-gradient(135deg, ${opMeta.color}, ${opMeta.color}dd)`,
                  border: 'none', color: '#fff', fontWeight: 800, fontSize: 15, cursor: 'pointer',
                  boxShadow: `0 4px 16px ${opMeta.color}66`,
                  opacity: scanMutation.isPending ? 0.7 : 1,
                }}
              >{scanMutation.isPending ? 'Working…' : `Confirm ${opMeta.label}`}</button>
            </div>
          </div>
        </div>
      )}

      {/* Bulk confirm popup — shown when operator presses "Confirm All" in
          bulk mode. Displays the aggregate totals before committing. */}
      {showBulkConfirm && (
        <div
          onClick={() => { if (!isCommittingBulk) setShowBulkConfirm(false) }}
          style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.78)', zIndex: 70, display: 'flex', alignItems: 'flex-end' }}
        >
          <div onClick={(e) => e.stopPropagation()} style={{ width: '100%', background: '#0f172a', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 20, paddingBottom: 24, display: 'flex', flexDirection: 'column', gap: 14 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <div style={{ width: 38, height: 38, borderRadius: 19, background: `${opMeta.color}33`, border: `1px solid ${opMeta.color}88`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20 }}>📦</div>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 16, fontWeight: 800 }}>Confirm batch</div>
                <div style={{ fontSize: 11, color: '#94a3b8' }}>Are you sure? Review the totals below.</div>
              </div>
            </div>

            <div style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(148,163,184,0.18)', borderRadius: 12, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
              <Row label="Operation" value={opMeta.label} valueColor={opMeta.color} />
              {needsToWarehouse ? (
                <>
                  <Row label="From" value={selectedWarehouse?.name ?? '—'} />
                  <Row label="To" value={destinationWarehouse?.name ?? '—'} />
                </>
              ) : (
                <Row label="Warehouse" value={selectedWarehouse?.name ?? '—'} />
              )}
              <Row label="Boxes" value={`${bulkBoxCount} ${bulkBoxCount === 1 ? 'box' : 'boxes'}`} />
              {bulkKgTotal > 0 && <Row label="Total weight" value={`${formatQty(bulkKgTotal)} kg`} />}
              {bulkPcsTotal > 0 && <Row label="Total count" value={`${formatQty(bulkPcsTotal)} pcs`} />}
            </div>

            <div style={{ display: 'flex', gap: 10 }}>
              <button
                onClick={() => setShowBulkConfirm(false)}
                disabled={isCommittingBulk}
                style={{
                  flex: 1, padding: '14px 12px', borderRadius: 12,
                  background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.15)',
                  color: '#e2e8f0', fontWeight: 700, fontSize: 15, cursor: 'pointer',
                  opacity: isCommittingBulk ? 0.5 : 1,
                }}
              >Cancel</button>
              <button
                onClick={commitBulkQueue}
                disabled={isCommittingBulk}
                style={{
                  flex: 2, padding: '14px 12px', borderRadius: 12,
                  background: `linear-gradient(135deg, ${opMeta.color}, ${opMeta.color}dd)`,
                  border: 'none', color: '#fff', fontWeight: 800, fontSize: 15, cursor: 'pointer',
                  boxShadow: `0 4px 16px ${opMeta.color}66`,
                  opacity: isCommittingBulk ? 0.7 : 1,
                }}
              >{isCommittingBulk ? 'Working…' : `Confirm ${bulkBoxCount}`}</button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// Format a number for display — strip trailing zeros from the .0 fraction so
// integers render as "5" instead of "5.0" but decimals keep up to 2 places.
function formatQty(n: number): string {
  if (Number.isInteger(n)) return n.toString()
  return n.toFixed(2).replace(/\.?0+$/, '')
}

function Row({ label, value, mono, valueColor }: { label: string; value: string; mono?: boolean; valueColor?: string }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12 }}>
      <span style={{ fontSize: 11, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 600 }}>{label}</span>
      <span style={{
        fontSize: 14, fontWeight: 700, color: valueColor ?? '#f1f5f9',
        fontFamily: mono ? 'monospace' : undefined, textAlign: 'right',
      }}>{value}</span>
    </div>
  )
}

function resultToneStyle(result: ScanResult | null) {
  if (result?.noChange) {
    return { bg: 'rgba(250,204,21,0.18)', border: 'rgba(250,204,21,0.5)', text: '#fef9c3', title: '⚠ Already done' }
  }
  if (result?.type === 'USED') {
    return { bg: 'rgba(239,68,68,0.15)', border: 'rgba(239,68,68,0.45)', text: '#fecaca', title: '↑ Used / Out' }
  }
  if (result?.type === 'TRANSFER') {
    return { bg: 'rgba(59,130,246,0.18)', border: 'rgba(59,130,246,0.5)', text: '#bfdbfe', title: '⇄ Transferred' }
  }
  // IN
  return { bg: 'rgba(34,197,94,0.15)', border: 'rgba(34,197,94,0.45)', text: '#bbf7d0', title: '↓ Stocked' }
}
