import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { BrowserMultiFormatReader } from '@zxing/browser'
import { useAuthStore } from '../stores/authStore'
import { api } from '../api/client'
import { disconnectSocket } from '../lib/socket'
import { useScanStock } from '../api/stock'
import { useWarehouses } from '../api/warehouses'
import type { ScanResult, ScanPayload } from '../api/stock'

function playBeep(success: boolean) {
  try {
    const ctx = new (window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext)()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    osc.connect(gain); gain.connect(ctx.destination)
    if (success) {
      osc.frequency.setValueAtTime(880, ctx.currentTime)
      osc.frequency.setValueAtTime(1100, ctx.currentTime + 0.08)
      osc.type = 'sine'
      gain.gain.setValueAtTime(0.35, ctx.currentTime)
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.2)
      osc.start(ctx.currentTime); osc.stop(ctx.currentTime + 0.2)
    } else {
      osc.frequency.setValueAtTime(300, ctx.currentTime)
      osc.type = 'square'
      gain.gain.setValueAtTime(0.2, ctx.currentTime)
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.3)
      osc.start(ctx.currentTime); osc.stop(ctx.currentTime + 0.3)
    }
  } catch { /* noop */ }
}

function vibrate(pattern: number | number[]) {
  try { navigator.vibrate?.(pattern) } catch { /* noop */ }
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

// QR labels generated by /stock/labels encode JSON: {id}.
function parseStockQr(text: string): string | null {
  try {
    const obj = JSON.parse(text)
    if (!obj || typeof obj !== 'object') return null
    const id = (obj as { id?: unknown }).id
    if (typeof id !== 'string' || !UUID_RE.test(id)) return null
    return id
  } catch {
    return null
  }
}

const WH_KEY = 'stock-scan-warehouseId'

export default function StockScan() {
  const navigate = useNavigate()
  const user = useAuthStore((s) => s.user)
  const setUser = useAuthStore((s) => s.setUser)
  const { data: warehouses = [] } = useWarehouses()

  const videoRef = useRef<HTMLVideoElement>(null)
  const streamRef = useRef<MediaStream | null>(null)
  const controlsRef = useRef<{ stop: () => void } | null>(null)
  const lockedRef = useRef(false)

  const [warehouseId, setWarehouseId] = useState<string>(() => localStorage.getItem(WH_KEY) ?? '')
  const [showWhPicker, setShowWhPicker] = useState(false)
  const [cameraOn, setCameraOn] = useState(false)
  const [cameraError, setCameraError] = useState<string | null>(null)
  const [lastResult, setLastResult] = useState<ScanResult | null>(null)
  const [errorMessage, setErrorMessage] = useState<string | null>(null)

  const scanMutation = useScanStock()

  useEffect(() => {
    if (warehouseId) localStorage.setItem(WH_KEY, warehouseId)
  }, [warehouseId])

  // If only one warehouse exists, auto-select it
  useEffect(() => {
    if (!warehouseId && warehouses.length === 1) setWarehouseId(warehouses[0].id)
  }, [warehouses, warehouseId])

  const selectedWarehouse = warehouses.find((w) => w.id === warehouseId)

  const stopCamera = useCallback(() => {
    controlsRef.current?.stop()
    controlsRef.current = null
    streamRef.current?.getTracks().forEach((t) => t.stop())
    streamRef.current = null
    setCameraOn(false)
  }, [])

  const startCamera = useCallback(async () => {
    setCameraError(null); setErrorMessage(null)
    if (!warehouseId) {
      setShowWhPicker(true)
      return
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment', width: { ideal: 1280 }, height: { ideal: 720 } },
      })
      streamRef.current = stream
      setCameraOn(true)
    } catch (err: unknown) {
      const name = (err as { name?: string })?.name
      setCameraError(
        name === 'NotAllowedError' ? 'Camera permission denied. Please allow camera access.' :
        name === 'NotFoundError' ? 'No camera found on this device.' :
        'Could not open camera.',
      )
    }
  }, [warehouseId])

  useEffect(() => {
    if (!cameraOn || !videoRef.current || !streamRef.current) return
    const video = videoRef.current
    const stream = streamRef.current
    video.srcObject = stream
    const reader = new BrowserMultiFormatReader()

    video.play().then(() => {
      reader.decodeFromStream(stream, video, (result, _err, controls) => {
        if (controls && !controlsRef.current) controlsRef.current = controls
        if (!result || lockedRef.current) return
        const text = result.getText().trim()
        const id = parseStockQr(text)
        if (!id) return
        if (!warehouseId) {
          setErrorMessage('Pick a warehouse first.')
          return
        }
        lockedRef.current = true
        playBeep(true); vibrate(100)
        const payload: ScanPayload = { id, warehouseId }
        scanMutation.mutate(payload, {
          onSuccess: (data) => {
            setLastResult(data); setErrorMessage(null)
            window.setTimeout(() => { lockedRef.current = false }, 1500)
          },
          onError: (err: unknown) => {
            const msg = (err as { response?: { data?: { error?: string } } })?.response?.data?.error
              ?? 'Scan failed'
            setErrorMessage(msg); setLastResult(null)
            playBeep(false); vibrate([80, 60, 80])
            window.setTimeout(() => { lockedRef.current = false }, 1500)
          },
        })
      }).then((controls) => { if (!controlsRef.current) controlsRef.current = controls })
        .catch(() => { /* noop */ })
    }).catch(() => {
      setCameraError('Could not start video stream.')
      setCameraOn(false)
    })

    return () => {
      try { (reader as unknown as { stopAsyncDecode?: () => void }).stopAsyncDecode?.() } catch { /* noop */ }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cameraOn, warehouseId])

  useEffect(() => () => stopCamera(), [stopCamera])

  async function handleLogout() {
    try { await api.post('/auth/logout') } catch { /* ignore */ }
    disconnectSocket()
    setUser(null)
    navigate('/scan', { replace: true })
  }

  const resultStyle = resultToneStyle(lastResult?.type)

  return (
    <div style={{ minHeight: '100dvh', display: 'flex', flexDirection: 'column', background: '#0f172a', color: '#fff' }}>
      <header style={{
        padding: '14px 18px', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        background: 'rgba(15,23,42,0.95)', borderBottom: '1px solid rgba(148,163,184,0.2)',
      }}>
        <div>
          <div style={{ fontSize: 13, fontWeight: 700, letterSpacing: '0.04em' }}>STOCK SCAN</div>
          <div style={{ fontSize: 11, color: '#94a3b8' }}>{user?.username}</div>
        </div>
        <button
          onClick={handleLogout}
          style={{ background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.15)',
            color: '#f1f5f9', padding: '7px 14px', borderRadius: 8, fontSize: 12, fontWeight: 600, cursor: 'pointer' }}
        >Sign Out</button>
      </header>

      {/* Warehouse selector */}
      <button
        onClick={() => setShowWhPicker(true)}
        style={{
          margin: '12px 14px 4px', padding: '12px 16px', borderRadius: 10,
          background: selectedWarehouse ? 'rgba(59,130,246,0.16)' : 'rgba(239,68,68,0.18)',
          border: `1px solid ${selectedWarehouse ? 'rgba(59,130,246,0.4)' : 'rgba(239,68,68,0.5)'}`,
          color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10,
        }}
      >
        <span style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}>
          <span style={{ fontSize: 11, opacity: 0.8, fontWeight: 500 }}>WAREHOUSE</span>
          <span style={{ fontSize: 14, fontWeight: 700 }}>
            {selectedWarehouse ? selectedWarehouse.name : 'Select warehouse'}
          </span>
        </span>
        <span style={{ fontSize: 11, opacity: 0.8 }}>change ›</span>
      </button>

      <div style={{ flex: 1, position: 'relative', overflow: 'hidden', background: '#000' }}>
        {cameraOn ? (
          <>
            <video ref={videoRef} playsInline muted style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', pointerEvents: 'none' }}>
              <div style={{ width: '70%', maxWidth: 280, aspectRatio: '1/1', border: '3px solid rgba(34,197,94,0.85)', borderRadius: 14, boxShadow: '0 0 0 9999px rgba(0,0,0,0.5)' }} />
            </div>
          </>
        ) : (
          <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 16, padding: 20 }}>
            <div style={{ fontSize: 52 }}>📦</div>
            <div style={{ fontSize: 17, fontWeight: 700, textAlign: 'center' }}>Ready to scan stock items</div>
            <div style={{ fontSize: 13, color: '#94a3b8', textAlign: 'center', maxWidth: 280 }}>
              {selectedWarehouse
                ? <>Scanning into <strong style={{ color: '#fff' }}>{selectedWarehouse.name}</strong>. Same warehouse → <span style={{ color: '#ef4444' }}>USED</span>; different warehouse → <span style={{ color: '#3b82f6' }}>TRANSFER</span>.</>
                : <>First select a warehouse above, then open the camera.</>}
            </div>
            {cameraError && (
              <div style={{ background: 'rgba(239,68,68,0.15)', border: '1px solid rgba(239,68,68,0.4)', color: '#fecaca', padding: '10px 14px', borderRadius: 8, fontSize: 13, maxWidth: 320, textAlign: 'center' }}>
                {cameraError}
              </div>
            )}
            <button
              onClick={startCamera}
              style={{ marginTop: 4, padding: '14px 28px',
                background: 'linear-gradient(135deg, #22c55e, #16a34a)', color: '#fff', border: 'none',
                borderRadius: 12, fontSize: 15, fontWeight: 700, cursor: 'pointer',
                boxShadow: '0 4px 18px rgba(34,197,94,0.4)', minHeight: 52, minWidth: 180 }}
            >Open Camera</button>
          </div>
        )}
      </div>

      <div style={{ padding: '14px 18px', minHeight: 88, background: '#0f172a', borderTop: '1px solid rgba(148,163,184,0.15)' }}>
        {errorMessage ? (
          <div style={{ background: 'rgba(239,68,68,0.15)', border: '1px solid rgba(239,68,68,0.4)', color: '#fecaca', padding: 14, borderRadius: 10 }}>
            <div style={{ fontWeight: 700, fontSize: 14 }}>✗ {errorMessage}</div>
            <div style={{ fontSize: 12, color: '#fda4af' }}>Try another QR or check the label.</div>
          </div>
        ) : lastResult ? (
          <div style={{
            background: resultStyle.bg, border: `1px solid ${resultStyle.border}`, color: resultStyle.text,
            padding: 14, borderRadius: 10, display: 'flex', flexDirection: 'column', gap: 4,
          }}>
            <div style={{ fontWeight: 800, fontSize: 15 }}>{resultStyle.title}</div>
            <div style={{ fontSize: 13 }}>
              {lastResult.item.productName} · {lastResult.item.quantity}{' '}
              {lastResult.item.unit === 'KG' ? 'kg' : 'pcs'} · Batch {lastResult.item.batchNumber}
            </div>
            {lastResult.fromWarehouse && lastResult.toWarehouse && lastResult.type === 'TRANSFER' && (
              <div style={{ fontSize: 12, opacity: 0.85 }}>
                {lastResult.fromWarehouse} → {lastResult.toWarehouse}
              </div>
            )}
          </div>
        ) : (
          <div style={{ color: '#94a3b8', fontSize: 13, textAlign: 'center', padding: '24px 0' }}>
            Last scan result will appear here.
          </div>
        )}
      </div>

      {showWhPicker && (
        <div
          onClick={() => setShowWhPicker(false)}
          style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', zIndex: 50, display: 'flex', alignItems: 'flex-end' }}
        >
          <div onClick={(e) => e.stopPropagation()} style={{ width: '100%', background: '#0f172a', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 16, maxHeight: '70vh', overflow: 'auto' }}>
            <div style={{ fontSize: 14, fontWeight: 700, marginBottom: 10 }}>Pick warehouse</div>
            {warehouses.length === 0 ? (
              <div style={{ color: '#94a3b8', fontSize: 13 }}>No warehouses configured. Ask an admin to create one.</div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                {warehouses.map((w) => (
                  <button
                    key={w.id}
                    onClick={() => { setWarehouseId(w.id); setShowWhPicker(false) }}
                    style={{
                      padding: '12px 14px', textAlign: 'left', borderRadius: 10,
                      background: warehouseId === w.id ? 'rgba(59,130,246,0.25)' : 'rgba(255,255,255,0.05)',
                      border: `1px solid ${warehouseId === w.id ? 'rgba(59,130,246,0.5)' : 'rgba(255,255,255,0.1)'}`,
                      color: '#fff', fontSize: 14, fontWeight: 600, cursor: 'pointer',
                    }}
                  >
                    <div>{w.name}</div>
                    <div style={{ fontSize: 11, opacity: 0.7, fontWeight: 400 }}>{w.address}</div>
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

function resultToneStyle(type: ScanResult['type'] | undefined) {
  if (type === 'USED') {
    return { bg: 'rgba(239,68,68,0.15)', border: 'rgba(239,68,68,0.45)', text: '#fecaca', title: '↑ Used / Out' }
  }
  if (type === 'TRANSFER') {
    return { bg: 'rgba(59,130,246,0.18)', border: 'rgba(59,130,246,0.5)', text: '#bfdbfe', title: '⇄ Transferred' }
  }
  // IN
  return { bg: 'rgba(34,197,94,0.15)', border: 'rgba(34,197,94,0.45)', text: '#bbf7d0', title: '↓ Stocked' }
}
