import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { BrowserMultiFormatReader } from '@zxing/browser'
import { useAuthStore } from '../stores/authStore'
import { api } from '../api/client'
import { disconnectSocket } from '../lib/socket'
import { useScanStock } from '../api/stock'
import { useWarehouses } from '../api/warehouses'
import type { ScanResult, ScanPayload, ScanOperation } from '../api/stock'

function playBeep(success: boolean) {
  try {
    const ctx = new (window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext)()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    osc.connect(gain); gain.connect(ctx.destination)
    if (success) {
      osc.frequency.setValueAtTime(880, ctx.currentTime)
      osc.frequency.setValueAtTime(1100, ctx.currentTime + 0.08)
      osc.type = 'sine'
      gain.gain.setValueAtTime(0.35, ctx.currentTime)
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.2)
      osc.start(ctx.currentTime); osc.stop(ctx.currentTime + 0.2)
    } else {
      osc.frequency.setValueAtTime(300, ctx.currentTime)
      osc.type = 'square'
      gain.gain.setValueAtTime(0.2, ctx.currentTime)
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.3)
      osc.start(ctx.currentTime); osc.stop(ctx.currentTime + 0.3)
    }
  } catch { /* noop */ }
}

function vibrate(pattern: number | number[]) {
  try { navigator.vibrate?.(pattern) } catch { /* noop */ }
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

// QR labels generated by /stock/labels encode JSON {id} — but be lenient and
// accept either a raw UUID string or { id: "<uuid>" } JSON.
function parseStockQr(text: string): string | null {
  const trimmed = text.trim()
  if (UUID_RE.test(trimmed)) return trimmed
  try {
    const obj = JSON.parse(trimmed)
    if (obj && typeof obj === 'object') {
      const id = (obj as { id?: unknown }).id
      if (typeof id === 'string' && UUID_RE.test(id)) return id
    }
  } catch { /* not JSON */ }
  return null
}

const WH_KEY = 'stock-scan-warehouseId'
const OP_KEY = 'stock-scan-operation'

const OPERATIONS: { value: ScanOperation; label: string; subtitle: string; color: string }[] = [
  { value: 'IN',       label: 'Stock In',       subtitle: 'Receive into warehouse', color: '#22c55e' },
  { value: 'OUT',      label: 'Stock Out',      subtitle: 'Mark as used / shipped',  color: '#ef4444' },
  { value: 'TRANSFER', label: 'Stock Transfer', subtitle: 'Move between warehouses', color: '#3b82f6' },
]

export default function StockScan() {
  const navigate = useNavigate()
  const user = useAuthStore((s) => s.user)
  const setUser = useAuthStore((s) => s.setUser)
  const { data: warehouses = [] } = useWarehouses()

  const videoRef = useRef<HTMLVideoElement>(null)
  const streamRef = useRef<MediaStream | null>(null)
  const controlsRef = useRef<{ stop: () => void } | null>(null)
  const lockedRef = useRef(false)

  const [operation, setOperation] = useState<ScanOperation>(() => {
    const stored = localStorage.getItem(OP_KEY) as ScanOperation | null
    return stored && ['IN', 'OUT', 'TRANSFER'].includes(stored) ? stored : 'IN'
  })
  const [warehouseId, setWarehouseId] = useState<string>(() => localStorage.getItem(WH_KEY) ?? '')
  const [toWarehouseId, setToWarehouseId] = useState<string>('')
  const [showOpPicker, setShowOpPicker] = useState(false)
  const [showWhPicker, setShowWhPicker] = useState<null | 'from' | 'to'>(null)
  const [cameraOn, setCameraOn] = useState(false)
  const [cameraError, setCameraError] = useState<string | null>(null)
  const [lastResult, setLastResult] = useState<ScanResult | null>(null)
  const [errorMessage, setErrorMessage] = useState<string | null>(null)
  const [debugRaw, setDebugRaw] = useState<string | null>(null)
  const [showDebug, setShowDebug] = useState(false)
  const [pendingScan, setPendingScan] = useState<{ id: string } | null>(null)
  const pendingRef = useRef<{ id: string } | null>(null)

  useEffect(() => { pendingRef.current = pendingScan }, [pendingScan])

  const scanMutation = useScanStock()

  useEffect(() => {
    if (warehouseId) localStorage.setItem(WH_KEY, warehouseId)
  }, [warehouseId])
  useEffect(() => {
    localStorage.setItem(OP_KEY, operation)
  }, [operation])

  useEffect(() => {
    if (!warehouseId && warehouses.length === 1) setWarehouseId(warehouses[0].id)
  }, [warehouses, warehouseId])

  const selectedWarehouse = warehouses.find((w) => w.id === warehouseId)
  const destinationWarehouse = warehouses.find((w) => w.id === toWarehouseId)
  const opMeta = OPERATIONS.find((o) => o.value === operation)!
  const needsToWarehouse = operation === 'TRANSFER'

  const ready = !!warehouseId && (!needsToWarehouse || !!toWarehouseId) && warehouseId !== toWarehouseId

  const stopCamera = useCallback(() => {
    controlsRef.current?.stop()
    controlsRef.current = null
    streamRef.current?.getTracks().forEach((t) => t.stop())
    streamRef.current = null
    setCameraOn(false)
  }, [])

  const startCamera = useCallback(async () => {
    setCameraError(null); setErrorMessage(null)
    if (!warehouseId) { setShowWhPicker('from'); return }
    if (needsToWarehouse && !toWarehouseId) { setShowWhPicker('to'); return }
    if (needsToWarehouse && warehouseId === toWarehouseId) {
      setErrorMessage('Source and destination warehouses must differ.')
      return
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment', width: { ideal: 1280 }, height: { ideal: 720 } },
      })
      streamRef.current = stream
      setCameraOn(true)
    } catch (err: unknown) {
      const name = (err as { name?: string })?.name
      setCameraError(
        name === 'NotAllowedError' ? 'Camera permission denied. Please allow camera access.' :
        name === 'NotFoundError' ? 'No camera found on this device.' :
        'Could not open camera.',
      )
    }
  }, [warehouseId, toWarehouseId, needsToWarehouse])

  useEffect(() => {
    if (!cameraOn || !videoRef.current || !streamRef.current) return
    const video = videoRef.current
    const stream = streamRef.current
    video.srcObject = stream
    const reader = new BrowserMultiFormatReader()

    video.play().then(() => {
      reader.decodeFromStream(stream, video, (result, _err, controls) => {
        if (controls && !controlsRef.current) controlsRef.current = controls
        if (!result || lockedRef.current || pendingRef.current) return
        const text = result.getText().trim()
        setDebugRaw(text)
        const id = parseStockQr(text)
        if (!id) {
          setErrorMessage('Unknown QR — not a stock label.')
          playBeep(false); vibrate([80, 60, 80])
          window.setTimeout(() => setErrorMessage(null), 1800)
          return
        }
        if (!ready) {
          setErrorMessage('Pick operation and warehouse(s) first.')
          return
        }
        // QR detected — alert user, lock further detection, and ask them
        // to confirm before we actually commit the operation.
        playBeep(true); vibrate(100)
        setPendingScan({ id })
      }).then((controls) => { if (!controlsRef.current) controlsRef.current = controls })
        .catch(() => { /* noop */ })
    }).catch(() => {
      setCameraError('Could not start video stream.')
      setCameraOn(false)
    })

    return () => {
      try { (reader as unknown as { stopAsyncDecode?: () => void }).stopAsyncDecode?.() } catch { /* noop */ }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cameraOn, warehouseId, toWarehouseId, operation, needsToWarehouse, ready])

  useEffect(() => () => stopCamera(), [stopCamera])

  function cancelScan() {
    setPendingScan(null)
  }

  function confirmScan() {
    if (!pendingScan) return
    const payload: ScanPayload = {
      id: pendingScan.id,
      operation,
      warehouseId,
      ...(needsToWarehouse ? { toWarehouseId } : {}),
    }
    scanMutation.mutate(payload, {
      onSuccess: (data) => {
        setLastResult(data); setErrorMessage(null)
        setPendingScan(null)
        playBeep(true); vibrate(200)
      },
      onError: (err: unknown) => {
        const msg = (err as { response?: { data?: { error?: string } } })?.response?.data?.error
          ?? 'Scan failed'
        setErrorMessage(msg); setLastResult(null)
        setPendingScan(null)
        playBeep(false); vibrate([80, 60, 80])
      },
    })
  }

  async function handleLogout() {
    try { await api.post('/auth/logout') } catch { /* ignore */ }
    disconnectSocket()
    setUser(null)
    navigate('/scan', { replace: true })
  }

  const resultStyle = resultToneStyle(lastResult)

  return (
    <div style={{ minHeight: '100dvh', display: 'flex', flexDirection: 'column', background: '#0f172a', color: '#fff' }}>
      <header style={{
        padding: '14px 18px', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        background: 'rgba(15,23,42,0.95)', borderBottom: '1px solid rgba(148,163,184,0.2)',
      }}>
        <div>
          <div style={{ fontSize: 13, fontWeight: 700, letterSpacing: '0.04em' }}>STOCK SCAN</div>
          <div style={{ fontSize: 11, color: '#94a3b8' }}>{user?.username}</div>
        </div>
        <button
          onClick={handleLogout}
          style={{ background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.15)',
            color: '#f1f5f9', padding: '7px 14px', borderRadius: 8, fontSize: 12, fontWeight: 600, cursor: 'pointer' }}
        >Sign Out</button>
      </header>

      <div style={{ flex: 1, position: 'relative', overflow: 'hidden', background: '#000' }}>
        {cameraOn ? (
          <>
            <video ref={videoRef} playsInline muted style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', pointerEvents: 'none' }}>
              <div style={{ width: '70%', maxWidth: 280, aspectRatio: '1/1', border: `3px solid ${opMeta.color}d9`, borderRadius: 14, boxShadow: '0 0 0 9999px rgba(0,0,0,0.5)' }} />
            </div>
            {showDebug && debugRaw && (
              <div style={{
                position: 'absolute', left: 12, right: 12, bottom: 12,
                background: 'rgba(0,0,0,0.85)', color: '#bbf7d0', padding: '8px 12px',
                borderRadius: 8, fontSize: 11, fontFamily: 'monospace',
                maxHeight: 80, overflow: 'auto', wordBreak: 'break-all',
              }}>
                <div style={{ color: '#94a3b8', fontWeight: 700, marginBottom: 2 }}>RAW QR</div>
                {debugRaw}
              </div>
            )}
          </>
        ) : (
          <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 16, padding: 20 }}>
            <div style={{ fontSize: 52 }}>📦</div>
            <div style={{ fontSize: 17, fontWeight: 700, textAlign: 'center' }}>{opMeta.label}</div>
            <div style={{ fontSize: 13, color: '#94a3b8', textAlign: 'center', maxWidth: 280 }}>
              {opMeta.subtitle}
              {selectedWarehouse && !needsToWarehouse && <> at <strong style={{ color: '#fff' }}>{selectedWarehouse.name}</strong></>}
              {selectedWarehouse && needsToWarehouse && destinationWarehouse && (
                <> · <strong style={{ color: '#fff' }}>{selectedWarehouse.name}</strong> → <strong style={{ color: '#fff' }}>{destinationWarehouse.name}</strong></>
              )}
            </div>
            {cameraError && (
              <div style={{ background: 'rgba(239,68,68,0.15)', border: '1px solid rgba(239,68,68,0.4)', color: '#fecaca', padding: '10px 14px', borderRadius: 8, fontSize: 13, maxWidth: 320, textAlign: 'center' }}>
                {cameraError}
              </div>
            )}
            <button
              onClick={startCamera}
              style={{ marginTop: 4, padding: '14px 28px',
                background: `linear-gradient(135deg, ${opMeta.color}, ${opMeta.color}dd)`, color: '#fff', border: 'none',
                borderRadius: 12, fontSize: 15, fontWeight: 700, cursor: 'pointer',
                boxShadow: `0 4px 18px ${opMeta.color}66`, minHeight: 52, minWidth: 180 }}
            >Open Camera</button>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, color: '#94a3b8', cursor: 'pointer' }}>
              <input type="checkbox" checked={showDebug} onChange={(e) => setShowDebug(e.target.checked)} />
              Show raw QR (debug)
            </label>
          </div>
        )}
      </div>

      <div style={{ padding: '10px 16px', background: '#0f172a', borderTop: '1px solid rgba(148,163,184,0.15)' }}>
        {errorMessage ? (
          <div style={{ background: 'rgba(239,68,68,0.15)', border: '1px solid rgba(239,68,68,0.4)', color: '#fecaca', padding: 14, borderRadius: 10 }}>
            <div style={{ fontWeight: 700, fontSize: 14 }}>✗ {errorMessage}</div>
            <div style={{ fontSize: 12, color: '#fda4af' }}>Try another QR or check the label.</div>
          </div>
        ) : lastResult ? (
          <div style={{
            background: resultStyle.bg, border: `1px solid ${resultStyle.border}`, color: resultStyle.text,
            padding: 14, borderRadius: 10, display: 'flex', flexDirection: 'column', gap: 4,
          }}>
            <div style={{ fontWeight: 800, fontSize: 15 }}>{resultStyle.title}</div>
            {lastResult.message && (
              <div style={{ fontSize: 12, opacity: 0.85 }}>{lastResult.message}</div>
            )}
            <div style={{ fontSize: 13 }}>
              {lastResult.item.productName} · {lastResult.item.quantity}{' '}
              {lastResult.item.unit === 'KG' ? 'kg' : 'pcs'} · Batch {lastResult.item.batchNumber}
            </div>
            {lastResult.fromWarehouse && lastResult.toWarehouse && lastResult.type === 'TRANSFER' && (
              <div style={{ fontSize: 12, opacity: 0.85 }}>
                {lastResult.fromWarehouse} → {lastResult.toWarehouse}
              </div>
            )}
          </div>
        ) : (
          <div style={{ color: '#94a3b8', fontSize: 12, textAlign: 'center', padding: '6px 0' }}>
            Last scan result will appear here.
          </div>
        )}
      </div>

      <div style={{ padding: '8px 14px 14px', display: 'flex', flexDirection: 'column', gap: 8, background: '#0f172a', borderTop: '1px solid rgba(148,163,184,0.1)' }}>
        {/* Operation selector */}
        <button
          onClick={() => setShowOpPicker(true)}
          style={{
            padding: '10px 14px', borderRadius: 10,
            background: `${opMeta.color}28`,
            border: `1px solid ${opMeta.color}66`,
            color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10,
          }}
        >
          <span style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}>
            <span style={{ fontSize: 10, opacity: 0.8, fontWeight: 500 }}>OPERATION</span>
            <span style={{ fontSize: 14, fontWeight: 700 }}>{opMeta.label}</span>
          </span>
          <span style={{ fontSize: 11, opacity: 0.8 }}>change ›</span>
        </button>

        {/* Warehouse selector (source/current) */}
        <button
          onClick={() => setShowWhPicker('from')}
          style={{
            padding: '10px 14px', borderRadius: 10,
            background: selectedWarehouse ? 'rgba(59,130,246,0.16)' : 'rgba(239,68,68,0.18)',
            border: `1px solid ${selectedWarehouse ? 'rgba(59,130,246,0.4)' : 'rgba(239,68,68,0.5)'}`,
            color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10,
          }}
        >
          <span style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}>
            <span style={{ fontSize: 10, opacity: 0.8, fontWeight: 500 }}>
              {needsToWarehouse ? 'FROM WAREHOUSE' : 'WAREHOUSE'}
            </span>
            <span style={{ fontSize: 14, fontWeight: 700 }}>
              {selectedWarehouse ? selectedWarehouse.name : 'Select warehouse'}
            </span>
          </span>
          <span style={{ fontSize: 11, opacity: 0.8 }}>change ›</span>
        </button>

        {/* Destination warehouse (only for Transfer) */}
        {needsToWarehouse && (
          <button
            onClick={() => setShowWhPicker('to')}
            style={{
              padding: '10px 14px', borderRadius: 10,
              background: destinationWarehouse ? 'rgba(59,130,246,0.16)' : 'rgba(239,68,68,0.18)',
              border: `1px solid ${destinationWarehouse ? 'rgba(59,130,246,0.4)' : 'rgba(239,68,68,0.5)'}`,
              color: '#fff', fontSize: 13, fontWeight: 600, cursor: 'pointer',
              display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10,
            }}
          >
            <span style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}>
              <span style={{ fontSize: 10, opacity: 0.8, fontWeight: 500 }}>TO WAREHOUSE</span>
              <span style={{ fontSize: 14, fontWeight: 700 }}>
                {destinationWarehouse ? destinationWarehouse.name : 'Select destination'}
              </span>
            </span>
            <span style={{ fontSize: 11, opacity: 0.8 }}>change ›</span>
          </button>
        )}
      </div>

      {/* Operation picker bottom sheet */}
      {showOpPicker && (
        <div
          onClick={() => setShowOpPicker(false)}
          style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', zIndex: 50, display: 'flex', alignItems: 'flex-end' }}
        >
          <div onClick={(e) => e.stopPropagation()} style={{ width: '100%', background: '#0f172a', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 16, maxHeight: '70vh', overflow: 'auto' }}>
            <div style={{ fontSize: 14, fontWeight: 700, marginBottom: 10 }}>Pick operation</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {OPERATIONS.map((o) => (
                <button
                  key={o.value}
                  onClick={() => { setOperation(o.value); setShowOpPicker(false); if (o.value !== 'TRANSFER') setToWarehouseId('') }}
                  style={{
                    padding: '12px 14px', textAlign: 'left', borderRadius: 10,
                    background: operation === o.value ? `${o.color}33` : 'rgba(255,255,255,0.05)',
                    border: `1px solid ${operation === o.value ? `${o.color}88` : 'rgba(255,255,255,0.1)'}`,
                    color: '#fff', fontSize: 14, fontWeight: 600, cursor: 'pointer',
                  }}
                >
                  <div>{o.label}</div>
                  <div style={{ fontSize: 11, opacity: 0.7, fontWeight: 400 }}>{o.subtitle}</div>
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Warehouse picker bottom sheet */}
      {showWhPicker && (
        <div
          onClick={() => setShowWhPicker(null)}
          style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', zIndex: 50, display: 'flex', alignItems: 'flex-end' }}
        >
          <div onClick={(e) => e.stopPropagation()} style={{ width: '100%', background: '#0f172a', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 16, maxHeight: '70vh', overflow: 'auto' }}>
            <div style={{ fontSize: 14, fontWeight: 700, marginBottom: 10 }}>
              {showWhPicker === 'to' ? 'Pick destination warehouse' : 'Pick warehouse'}
            </div>
            {warehouses.length === 0 ? (
              <div style={{ color: '#94a3b8', fontSize: 13 }}>No warehouses configured. Ask an admin to create one.</div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                {warehouses.map((w) => {
                  const selectedId = showWhPicker === 'to' ? toWarehouseId : warehouseId
                  return (
                    <button
                      key={w.id}
                      onClick={() => {
                        if (showWhPicker === 'to') setToWarehouseId(w.id)
                        else setWarehouseId(w.id)
                        setShowWhPicker(null)
                      }}
                      style={{
                        padding: '12px 14px', textAlign: 'left', borderRadius: 10,
                        background: selectedId === w.id ? 'rgba(59,130,246,0.25)' : 'rgba(255,255,255,0.05)',
                        border: `1px solid ${selectedId === w.id ? 'rgba(59,130,246,0.5)' : 'rgba(255,255,255,0.1)'}`,
                        color: '#fff', fontSize: 14, fontWeight: 600, cursor: 'pointer',
                      }}
                    >
                      <div>{w.name}</div>
                      <div style={{ fontSize: 11, opacity: 0.7, fontWeight: 400 }}>{w.address}</div>
                    </button>
                  )
                })}
              </div>
            )}
          </div>
        </div>
      )}

      {/* Scan confirmation modal — shown when a QR is detected and we are
          waiting for the operator to confirm the action. Camera keeps
          running but pendingRef prevents re-detection until resolved. */}
      {pendingScan && (
        <div
          style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.78)', zIndex: 60, display: 'flex', alignItems: 'flex-end' }}
        >
          <div style={{ width: '100%', background: '#0f172a', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 20, paddingBottom: 24, display: 'flex', flexDirection: 'column', gap: 14 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <div style={{ width: 38, height: 38, borderRadius: 19, background: `${opMeta.color}33`, border: `1px solid ${opMeta.color}88`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20 }}>📦</div>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 16, fontWeight: 800 }}>Confirm scan</div>
                <div style={{ fontSize: 11, color: '#94a3b8' }}>QR detected — review and confirm.</div>
              </div>
            </div>

            <div style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(148,163,184,0.18)', borderRadius: 12, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
              <Row label="Operation" value={opMeta.label} valueColor={opMeta.color} />
              {needsToWarehouse ? (
                <>
                  <Row label="From" value={selectedWarehouse?.name ?? '—'} />
                  <Row label="To" value={destinationWarehouse?.name ?? '—'} />
                </>
              ) : (
                <Row label="Warehouse" value={selectedWarehouse?.name ?? '—'} />
              )}
              <Row label="QR" value={pendingScan.id.slice(0, 8) + '…'} mono />
            </div>

            <div style={{ display: 'flex', gap: 10 }}>
              <button
                onClick={cancelScan}
                disabled={scanMutation.isPending}
                style={{
                  flex: 1, padding: '14px 12px', borderRadius: 12,
                  background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.15)',
                  color: '#e2e8f0', fontWeight: 700, fontSize: 15, cursor: 'pointer',
                  opacity: scanMutation.isPending ? 0.5 : 1,
                }}
              >Cancel</button>
              <button
                onClick={confirmScan}
                disabled={scanMutation.isPending}
                style={{
                  flex: 2, padding: '14px 12px', borderRadius: 12,
                  background: `linear-gradient(135deg, ${opMeta.color}, ${opMeta.color}dd)`,
                  border: 'none', color: '#fff', fontWeight: 800, fontSize: 15, cursor: 'pointer',
                  boxShadow: `0 4px 16px ${opMeta.color}66`,
                  opacity: scanMutation.isPending ? 0.7 : 1,
                }}
              >{scanMutation.isPending ? 'Working…' : `Confirm ${opMeta.label}`}</button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function Row({ label, value, mono, valueColor }: { label: string; value: string; mono?: boolean; valueColor?: string }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12 }}>
      <span style={{ fontSize: 11, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 600 }}>{label}</span>
      <span style={{
        fontSize: 14, fontWeight: 700, color: valueColor ?? '#f1f5f9',
        fontFamily: mono ? 'monospace' : undefined, textAlign: 'right',
      }}>{value}</span>
    </div>
  )
}

function resultToneStyle(result: ScanResult | null) {
  if (result?.noChange) {
    return { bg: 'rgba(250,204,21,0.18)', border: 'rgba(250,204,21,0.5)', text: '#fef9c3', title: '⚠ Already done' }
  }
  if (result?.type === 'USED') {
    return { bg: 'rgba(239,68,68,0.15)', border: 'rgba(239,68,68,0.45)', text: '#fecaca', title: '↑ Used / Out' }
  }
  if (result?.type === 'TRANSFER') {
    return { bg: 'rgba(59,130,246,0.18)', border: 'rgba(59,130,246,0.5)', text: '#bfdbfe', title: '⇄ Transferred' }
  }
  // IN
  return { bg: 'rgba(34,197,94,0.15)', border: 'rgba(34,197,94,0.45)', text: '#bbf7d0', title: '↓ Stocked' }
}
